version: '3.3'

services:
   web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        - ./www:/www
      depends_on:
        - php
   db:
     image: mysql:5.7
     ports:
       - '8082:3306'
     volumes:
       - ./database:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: test
       MYSQL_ROOT_PASSWORD: test
       MYSQL_USER: test
       MYSQL_PASSWORD: test
   php:
     build:
       context: ./docker/php-fpm
     volumes:
       - ./www:/www
     environment:
       XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
       PHP_IDE_CONFIG: "serverName=Docker"
volumes:
    db_data: {}

